# Generated by Django 4.1.1 on 2022-10-20 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_rantsanswermodel_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rantsquestionmodel',
            name='author',
        ),
        migrations.DeleteModel(
            name='RantsAnswerModel',
        ),
        migrations.DeleteModel(
            name='RantsQuestionModel',
        ),
    ]
