# Generated by Django 4.1.2 on 2022-10-27 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_remove_profile_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='avatar.png', upload_to='profile_pic'),
        ),
    ]
